require_relative '../node_modules/react-native/scripts/react_native_pods'


platform :ios, '17.0'

prepare_react_native_project!

target 'BlackKingdom' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath]
    )
  end
end